<?php

namespace Sub2GamingAqua\CustomGUIPlus;

//Essential Class
use pocketmine\Server;
use pocketmine\Player;

//Listener Class
use pocketmine\event\Listener;

use pocketmine\inventory\DoubleChestInventory;
use pocketmine\inventory\ChestInventory;

//Main Class
use Sub2GamingAqua\CustomGUIPlus\Main;

//Item Class
use pocketmine\item\Item;

//Vector3 Class
use pocketmine\math\Vector3;

//Config Class
use pocketmine\utils\Config;

//Events Class
use pocketmine\event\player\PlayerInteractEvent;

class EventListener implements Listener
{
  public function __construct(Main $main, Config $config, Config $database, Config $player){
  $this->Main = $main;
  $this->Config = $config;
  $this->Database = $database;
  $this->Player = $player;
  }
  public function onInteract(PlayerInteractEvent $event){
    $player = $event->getPlayer();
    $block = $event->getBlock();
    if($this->Player->getNested($player->getName().".command") == true){
      if($block->getId() == Item::CHEST or $block->getId() == Block::TRAPPED_CHEST){
        $name = $this->Player->getNested($player->getName().".name");
        $event->setCancelled(true);
        $this->Player->setNested($player->getName(), false);
        $this->Player->save();
        $tile = $block->getLevel()->getTile(new Vector3($block->x, $block->y, $block->z));
        $inv = $tile->getInventory();
        if($inv instanceof DoubleChestInventory){
          $id1 = $inv->getItem(0)->getId();
          $id2 = $inv->getItem(1)->getId();
          $id3 = $inv->getItem(2)->getId();
          $id4 = $inv->getItem(3)->getId();
          $id5 = $inv->getItem(4)->getId();
          $id6 = $inv->getItem(5)->getId();
          $id7 = $inv->getItem(6)->getId();
          $id8 = $inv->getItem(7)->getId();
          $id9 = $inv->getItem(8)->getId();
          $id10 = $inv->getItem(9)->getId();
          $id11 = $inv->getItem(10)->getId();
          $id12 = $inv->getItem(11)->getId();
          $id13 = $inv->getItem(12)->getId();
          $id14 = $inv->getItem(13)->getId();
          $id15 = $inv->getItem(14)->getId();
          $id16 = $inv->getItem(15)->getId();
          $id17 = $inv->getItem(16)->getId();
          $id18 = $inv->getItem(17)->getId();
          $id19 = $inv->getItem(18)->getId();
          $id20 = $inv->getItem(19)->getId();
          $id21 = $inv->getItem(20)->getId();
          $id22 = $inv->getItem(21)->getId();
          $id23 = $inv->getItem(22)->getId();
          $id24 = $inv->getItem(23)->getId();
          $id25 = $inv->getItem(24)->getId();
          $id26 = $inv->getItem(25)->getId();
          $id27 = $inv->getItem(26)->getId();
          $id28 = $inv->getItem(27)->getId();
          $id29 = $inv->getItem(28)->getId();
          $id30 = $inv->getItem(29)->getId();
          $id31 = $inv->getItem(30)->getId();
          $id32 = $inv->getItem(31)->getId();
          $id33 = $inv->getItem(32)->getId();
          $id34 = $inv->getItem(33)->getId();
          $id35 = $inv->getItem(34)->getId();
          $id36 = $inv->getItem(35)->getId();
          $id37 = $inv->getItem(36)->getId();
          $id38 = $inv->getItem(37)->getId();
          $id39 = $inv->getItem(38)->getId();
          $id40 = $inv->getItem(39)->getId();
          $id41 = $inv->getItem(40)->getId();
          $id42 = $inv->getItem(41)->getId();
          $id43 = $inv->getItem(42)->getId();
          $id44 = $inv->getItem(43)->getId();
          $id45 = $inv->getItem(44)->getId();
          $id46 = $inv->getItem(45)->getId();
          $id47 = $inv->getItem(46)->getId();
          $id48 = $inv->getItem(47)->getId();
          $id49 = $inv->getItem(48)->getId();
          $id50 = $inv->getItem(49)->getId();
          $id51 = $inv->getItem(50)->getId();
          $id52 = $inv->getItem(51)->getId();
          $id53 = $inv->getItem(52)->getId();
          $id54 = $inv->getItem(53)->getId();
          $meta1 = $inv->getItem(0)->getDamage();
          $meta2 = $inv->getItem(1)->getDamage();
          $meta3 = $inv->getItem(2)->getDamage();
          $meta4 = $inv->getItem(3)->getDamage();
          $meta5 = $inv->getItem(4)->getDamage();
          $meta6 = $inv->getItem(5)->getDamage();
          $meta7 = $inv->getItem(6)->getDamage();
          $meta8 = $inv->getItem(7)->getDamage();
          $meta9 = $inv->getItem(8)->getDamage();
          $meta10 = $inv->getItem(9)->getDamage();
          $meta11 = $inv->getItem(10)->getDamage();
          $meta12 = $inv->getItem(11)->getDamage();
          $meta13 = $inv->getItem(12)->getDamage();
          $meta14 = $inv->getItem(13)->getDamage();
          $meta15 = $inv->getItem(14)->getDamage();
          $meta16 = $inv->getItem(15)->getDamage();
          $meta17 = $inv->getItem(16)->getDamage();
          $meta18 = $inv->getItem(17)->getDamage();
          $meta19 = $inv->getItem(18)->getDamage();
          $meta20 = $inv->getItem(19)->getDamage();
          $meta21 = $inv->getItem(20)->getDamage();
          $meta22 = $inv->getItem(21)->getDamage();
          $meta23 = $inv->getItem(22)->getDamage();
          $meta24 = $inv->getItem(23)->getDamage();
          $meta25 = $inv->getItem(24)->getDamage();
          $meta26 = $inv->getItem(25)->getDamage();
          $meta27 = $inv->getItem(26)->getDamage();
          $meta28 = $inv->getItem(27)->getDamage();
          $meta29 = $inv->getItem(28)->getDamage();
          $meta30 = $inv->getItem(29)->getDamage();
          $meta31 = $inv->getItem(30)->getDamage();
          $meta32 = $inv->getItem(31)->getDamage();
          $meta33 = $inv->getItem(32)->getDamage();
          $meta34 = $inv->getItem(33)->getDamage();
          $meta35 = $inv->getItem(34)->getDamage();
          $meta36 = $inv->getItem(35)->getDamage();
          $meta37 = $inv->getItem(36)->getDamage();
          $meta38 = $inv->getItem(37)->getDamage();
          $meta39 = $inv->getItem(38)->getDamage();
          $meta40 = $inv->getItem(39)->getDamage();
          $meta41 = $inv->getItem(40)->getDamage();
          $meta42 = $inv->getItem(41)->getDamage();
          $meta43 = $inv->getItem(42)->getDamage();
          $meta44 = $inv->getItem(43)->getDamage();
          $meta45 = $inv->getItem(44)->getDamage();
          $meta46 = $inv->getItem(45)->getDamage();
          $meta47 = $inv->getItem(46)->getDamage();
          $meta48 = $inv->getItem(47)->getDamage();
          $meta49 = $inv->getItem(48)->getDamage();
          $meta50 = $inv->getItem(49)->getDamage();
          $meta51 = $inv->getItem(50)->getDamage();
          $meta52 = $inv->getItem(51)->getDamage();
          $meta53 = $inv->getItem(52)->getDamage();
          $meta54 = $inv->getItem(53)->getDamage();
          $this->Database->setNested($name.".Size", "TYPE_DOUBLE_CHEST");
          $this->Database->setNested($name.".readonly", true);
          $this->Database->setNested($name.".Interface".".id1", $id1);
          $this->Database->setNested($name.".Interface".".meta1", $meta1);
          $this->Database->setNested($name.".Interface".".id2", $id2);
          $this->Database->setNested($name.".Interface".".meta2", $meta2);
          $this->Database->setNested($name.".Interface".".id3", $id3);
          $this->Database->setNested($name.".Interface".".meta3", $meta3);
          $this->Database->setNested($name.".Interface".".id4", $id4);
          $this->Database->setNested($name.".Interface".".meta4", $meta4);
          $this->Database->setNested($name.".Interface".".id5", $id5);
          $this->Database->setNested($name.".Interface".".meta5", $meta5);
          $this->Database->setNested($name.".Interface".".id6", $id6);
          $this->Database->setNested($name.".Interface".".meta6", $meta6);
          $this->Database->setNested($name.".Interface".".id7", $id7);
          $this->Database->setNested($name.".Interface".".meta7", $meta7);
          $this->Database->setNested($name.".Interface".".id8", $id8);
          $this->Database->setNested($name.".Interface".".meta8", $meta8);
          $this->Database->setNested($name.".Interface".".id9", $id9);
          $this->Database->setNested($name.".Interface".".meta9", $meta9);
          $this->Database->setNested($name.".Interface".".id10", $id10);
          $this->Database->setNested($name.".Interface".".meta10", $meta10);
          $this->Database->setNested($name.".Interface".".id11", $id11);
          $this->Database->setNested($name.".Interface".".meta11", $meta11);
          $this->Database->setNested($name.".Interface".".id12", $id12);
          $this->Database->setNested($name.".Interface".".meta12", $meta12);
          $this->Database->setNested($name.".Interface".".id13", $id13);
          $this->Database->setNested($name.".Interface".".meta13", $meta13);
          $this->Database->setNested($name.".Interface".".id14", $id14);
          $this->Database->setNested($name.".Interface".".meta14", $meta14);
          $this->Database->setNested($name.".Interface".".id15", $id15);
          $this->Database->setNested($name.".Interface".".meta15", $meta15);
          $this->Database->setNested($name.".Interface".".id16", $id16);
          $this->Database->setNested($name.".Interface".".meta16", $meta16);
          $this->Database->setNested($name.".Interface".".id17", $id17);
          $this->Database->setNested($name.".Interface".".meta17", $meta17);
          $this->Database->setNested($name.".Interface".".id18", $id18);
          $this->Database->setNested($name.".Interface".".meta18", $meta18);
          $this->Database->setNested($name.".Interface".".id19", $id19);
          $this->Database->setNested($name.".Interface".".meta19", $meta19);
          $this->Database->setNested($name.".Interface".".id20", $id20);
          $this->Database->setNested($name.".Interface".".meta20", $meta20);
          $this->Database->setNested($name.".Interface".".id21", $id21);
          $this->Database->setNested($name.".Interface".".meta21", $meta21);
          $this->Database->setNested($name.".Interface".".id22", $id22);
          $this->Database->setNested($name.".Interface".".meta22", $meta22);
          $this->Database->setNested($name.".Interface".".id23", $id23);
          $this->Database->setNested($name.".Interface".".meta23", $meta23);
          $this->Database->setNested($name.".Interface".".id24", $id24);
          $this->Database->setNested($name.".Interface".".meta24", $meta24);
          $this->Database->setNested($name.".Interface".".id25", $id25);
          $this->Database->setNested($name.".Interface".".meta25", $meta25);
          $this->Database->setNested($name.".Interface".".id26", $id26);
          $this->Database->setNested($name.".Interface".".meta26", $meta26);
          $this->Database->setNested($name.".Interface".".id27", $id27);
          $this->Database->setNested($name.".Interface".".meta27", $meta27);
          $this->Database->setNested($name.".Interface".".id28", $id28);
          $this->Database->setNested($name.".Interface".".meta28", $meta28);
          $this->Database->setNested($name.".Interface".".id29", $id29);
          $this->Database->setNested($name.".Interface".".meta29", $meta29);
          $this->Database->setNested($name.".Interface".".id30", $id30);
          $this->Database->setNested($name.".Interface".".meta30", $meta30);
          $this->Database->setNested($name.".Interface".".id31", $id31);
          $this->Database->setNested($name.".Interface".".meta31", $meta31);
          $this->Database->setNested($name.".Interface".".id32", $id32);
          $this->Database->setNested($name.".Interface".".meta32", $meta32);
          $this->Database->setNested($name.".Interface".".id33", $id33);
          $this->Database->setNested($name.".Interface".".meta33", $meta33);
          $this->Database->setNested($name.".Interface".".id34", $id34);
          $this->Database->setNested($name.".Interface".".meta34", $meta34);
          $this->Database->setNested($name.".Interface".".id35", $id35);
          $this->Database->setNested($name.".Interface".".meta35", $meta35);
          $this->Database->setNested($name.".Interface".".id36", $id36);
          $this->Database->setNested($name.".Interface".".meta36", $meta36);
          $this->Database->setNested($name.".Interface".".id37", $id37);
          $this->Database->setNested($name.".Interface".".meta37", $meta37);
          $this->Database->setNested($name.".Interface".".id38", $id38);
          $this->Database->setNested($name.".Interface".".meta38", $meta38);
          $this->Database->setNested($name.".Interface".".id39", $id39);
          $this->Database->setNested($name.".Interface".".meta39", $meta39);
          $this->Database->setNested($name.".Interface".".id40", $id40);
          $this->Database->setNested($name.".Interface".".meta40", $meta40);
          $this->Database->setNested($name.".Interface".".id41", $id41);
          $this->Database->setNested($name.".Interface".".meta41", $meta41);
          $this->Database->setNested($name.".Interface".".id42", $id42);
          $this->Database->setNested($name.".Interface".".meta42", $meta42);
          $this->Database->setNested($name.".Interface".".id43", $id43);
          $this->Database->setNested($name.".Interface".".meta43", $meta43);
          $this->Database->setNested($name.".Interface".".id44", $id44);
          $this->Database->setNested($name.".Interface".".meta44", $meta44);
          $this->Database->setNested($name.".Interface".".id45", $id45);
          $this->Database->setNested($name.".Interface".".meta45", $meta45);
          $this->Database->setNested($name.".Interface".".id46", $id46);
          $this->Database->setNested($name.".Interface".".meta46", $meta46);
          $this->Database->setNested($name.".Interface".".id47", $id47);
          $this->Database->setNested($name.".Interface".".meta47", $meta47);
          $this->Database->setNested($name.".Interface".".id48", $id48);
          $this->Database->setNested($name.".Interface".".meta48", $meta48);
          $this->Database->setNested($name.".Interface".".id49", $id49);
          $this->Database->setNested($name.".Interface".".meta49", $meta49);
          $this->Database->setNested($name.".Interface".".id50", $id50);
          $this->Database->setNested($name.".Interface".".meta50", $meta50);
          $this->Database->setNested($name.".Interface".".id51", $id51);
          $this->Database->setNested($name.".Interface".".meta51", $meta51);
          $this->Database->setNested($name.".Interface".".id52", $id52);
          $this->Database->setNested($name.".Interface".".meta52", $meta52);
          $this->Database->setNested($name.".Interface".".id53", $id53);
          $this->Database->setNested($name.".Interface".".meta53", $meta53);
          $this->Database->setNested($name.".Interface".".id54", $id54);
          $this->Database->setNested($name.".Interface".".meta54", $meta54);
          $this->Database->save();
        }elseif($inv instanceof ChestInventory){
          $id1 = $inv->getItem(0)->getId();
          $id2 = $inv->getItem(1)->getId();
          $id3 = $inv->getItem(2)->getId();
          $id4 = $inv->getItem(3)->getId();
          $id5 = $inv->getItem(4)->getId();
          $id6 = $inv->getItem(5)->getId();
          $id7 = $inv->getItem(6)->getId();
          $id8 = $inv->getItem(7)->getId();
          $id9 = $inv->getItem(8)->getId();
          $id10 = $inv->getItem(9)->getId();
          $id11 = $inv->getItem(10)->getId();
          $id12 = $inv->getItem(11)->getId();
          $id13 = $inv->getItem(12)->getId();
          $id14 = $inv->getItem(13)->getId();
          $id15 = $inv->getItem(14)->getId();
          $id16 = $inv->getItem(15)->getId();
          $id17 = $inv->getItem(16)->getId();
          $id18 = $inv->getItem(17)->getId();
          $id19 = $inv->getItem(18)->getId();
          $id20 = $inv->getItem(19)->getId();
          $id21 = $inv->getItem(20)->getId();
          $id22 = $inv->getItem(21)->getId();
          $id23 = $inv->getItem(22)->getId();
          $id24 = $inv->getItem(23)->getId();
          $id25 = $inv->getItem(24)->getId();
          $id26 = $inv->getItem(25)->getId();
          $id27 = $inv->getItem(26)->getId();
          $meta1 = $inv->getItem(0)->getDamage();
          $meta2 = $inv->getItem(1)->getDamage();
          $meta3 = $inv->getItem(2)->getDamage();
          $meta4 = $inv->getItem(3)->getDamage();
          $meta5 = $inv->getItem(4)->getDamage();
          $meta6 = $inv->getItem(5)->getDamage();
          $meta7 = $inv->getItem(6)->getDamage();
          $meta8 = $inv->getItem(7)->getDamage();
          $meta9 = $inv->getItem(8)->getDamage();
          $meta10 = $inv->getItem(9)->getDamage();
          $meta11 = $inv->getItem(10)->getDamage();
          $meta12 = $inv->getItem(11)->getDamage();
          $meta13 = $inv->getItem(12)->getDamage();
          $meta14 = $inv->getItem(13)->getDamage();
          $meta15 = $inv->getItem(14)->getDamage();
          $meta16 = $inv->getItem(15)->getDamage();
          $meta17 = $inv->getItem(16)->getDamage();
          $meta18 = $inv->getItem(17)->getDamage();
          $meta19 = $inv->getItem(18)->getDamage();
          $meta20 = $inv->getItem(19)->getDamage();
          $meta21 = $inv->getItem(20)->getDamage();
          $meta22 = $inv->getItem(21)->getDamage();
          $meta23 = $inv->getItem(22)->getDamage();
          $meta24 = $inv->getItem(23)->getDamage();
          $meta25 = $inv->getItem(24)->getDamage();
          $meta26 = $inv->getItem(25)->getDamage();
          $meta27 = $inv->getItem(26)->getDamage();
          $this->Database->setNested($name.".Size", "TYPE_CHEST");
          $this->Database->setNested($name.".readonly", true);
          $this->Database->setNested($name.".Interface".".id1", $id1);
          $this->Database->setNested($name.".Interface".".meta1", $meta1);
          $this->Database->setNested($name.".Interface".".id2", $id2);
          $this->Database->setNested($name.".Interface".".meta2", $meta2);
          $this->Database->setNested($name.".Interface".".id3", $id3);
          $this->Database->setNested($name.".Interface".".meta3", $meta3);
          $this->Database->setNested($name.".Interface".".id4", $id4);
          $this->Database->setNested($name.".Interface".".meta4", $meta4);
          $this->Database->setNested($name.".Interface".".id5", $id5);
          $this->Database->setNested($name.".Interface".".meta5", $meta5);
          $this->Database->setNested($name.".Interface".".id6", $id6);
          $this->Database->setNested($name.".Interface".".meta6", $meta6);
          $this->Database->setNested($name.".Interface".".id7", $id7);
          $this->Database->setNested($name.".Interface".".meta7", $meta7);
          $this->Database->setNested($name.".Interface".".id8", $id8);
          $this->Database->setNested($name.".Interface".".meta8", $meta8);
          $this->Database->setNested($name.".Interface".".id9", $id9);
          $this->Database->setNested($name.".Interface".".meta9", $meta9);
          $this->Database->setNested($name.".Interface".".id10", $id10);
          $this->Database->setNested($name.".Interface".".meta10", $meta10);
          $this->Database->setNested($name.".Interface".".id11", $id11);
          $this->Database->setNested($name.".Interface".".meta11", $meta11);
          $this->Database->setNested($name.".Interface".".id12", $id12);
          $this->Database->setNested($name.".Interface".".meta12", $meta12);
          $this->Database->setNested($name.".Interface".".id13", $id13);
          $this->Database->setNested($name.".Interface".".meta13", $meta13);
          $this->Database->setNested($name.".Interface".".id14", $id14);
          $this->Database->setNested($name.".Interface".".meta14", $meta14);
          $this->Database->setNested($name.".Interface".".id15", $id15);
          $this->Database->setNested($name.".Interface".".meta15", $meta15);
          $this->Database->setNested($name.".Interface".".id16", $id16);
          $this->Database->setNested($name.".Interface".".meta16", $meta16);
          $this->Database->setNested($name.".Interface".".id17", $id17);
          $this->Database->setNested($name.".Interface".".meta17", $meta17);
          $this->Database->setNested($name.".Interface".".id18", $id18);
          $this->Database->setNested($name.".Interface".".meta18", $meta18);
          $this->Database->setNested($name.".Interface".".id19", $id19);
          $this->Database->setNested($name.".Interface".".meta19", $meta19);
          $this->Database->setNested($name.".Interface".".id20", $id20);
          $this->Database->setNested($name.".Interface".".meta20", $meta20);
          $this->Database->setNested($name.".Interface".".id21", $id21);
          $this->Database->setNested($name.".Interface".".meta21", $meta21);
          $this->Database->setNested($name.".Interface".".id22", $id22);
          $this->Database->setNested($name.".Interface".".meta22", $meta22);
          $this->Database->setNested($name.".Interface".".id23", $id23);
          $this->Database->setNested($name.".Interface".".meta23", $meta23);
          $this->Database->setNested($name.".Interface".".id24", $id24);
          $this->Database->setNested($name.".Interface".".meta24", $meta24);
          $this->Database->setNested($name.".Interface".".id25", $id25);
          $this->Database->setNested($name.".Interface".".meta25", $meta25);
          $this->Database->setNested($name.".Interface".".meta26", $meta26);
          $this->Database->setNested($name.".Interface".".id26", $id26);
          $this->Database->setNested($name.".Interface".".meta27", $meta27);
          $this->Database->setNested($name.".Interface".".id27", $id27);
          $this->Database->save();
        }
        $player->sendMessage("§f[§a+§f] §aGUI Has Been Successfully Added !");
        $this->Player->remove($player->getName());
      }
    }
  }
}
